# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_team_max_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='lastweek_position',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='lastweek_rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='max_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='max_position',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='max_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='min_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='min_position',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='min_rating',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='thisweek_position',
            field=models.IntegerField(default=1500),
        ),
        migrations.AddField(
            model_name='team',
            name='thisweek_rating',
            field=models.IntegerField(default=1500),
        ),
    ]
