# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_auto_20170417_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='played_matches',
            field=models.IntegerField(default=0),
        ),
    ]
