# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_team_played_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='week_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='lastweek_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_position',
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='team',
            name='max_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='min_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='min_rating',
            field=models.IntegerField(default=4000),
        ),
        migrations.AlterField(
            model_name='team',
            name='thisweek_position',
            field=models.IntegerField(default=0),
        ),
    ]
