# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0007_auto_20170426_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='awayteam_rating_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='hometeam_rating_before',
            field=models.IntegerField(default=0),
        ),
    ]
