# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0008_auto_20170426_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainheading', models.CharField(max_length=1000)),
                ('mainimage', models.ImageField(upload_to='')),
                ('subimage', models.ImageField(upload_to='')),
                ('subheading', models.CharField(blank=True, max_length=1000, null=True)),
                ('htmlcontent', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('footer', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
