# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0012_auto_20170520_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mainimage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subimage',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
